name: Deploy Ticket System Front-end Service

on:
  push:
    branches:
      - "main"

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
              node-version: [18.x]
        env:
            target: '/var/www/gruupA/ticketSystem/frontend'

            message: |
              [${{ github.event.head_commit.committer.name }}](https://github.com/${{github.event.head_commit.committer.username}}) pushed new commit: 
              `[ ${{github.event.head_commit.message}} ]` 
              to [${{ github.event.repository.name }}](https://github.com/${{github.event.repository.html_url}}) 
              You can now use it at https://ticketsystem.future-wave.co/
            
        steps:
          - name: Checkout code
            uses: actions/checkout@v2.4.2      

          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v2
            with:
              node-version: ${{ matrix.node-version }}

          - name: Install pnpm
            run: npm install -g pnpm

          - name: Install npm dependencies
            run: pnpm install

          - name: Build application
            run: pnpm run generate

          - name: copy via ssh
            uses: appleboy/scp-action@master
            with:
              host: ${{ secrets.SSH_HOST }}
              port: 22
              username: ${{ secrets.SSH_USERNAME }}
              password: ${{ secrets.SSH_PASSWORD }}
              source: .output/public/*
              target: "/var/www/groupA/ticketSystem/frontend"
              overwrite: true
              rm: false
              debug: true # Enable debugging
          - name: send notification to telegram
            uses: appleboy/telegram-action@master
            with:
                to: -1002235899879
                # to: 872819018
                token: 7327351568:AAGqfeI4QO-uxqAfv-9GIomJsUZiP6-J_tA
                message: ${{ env.message }}
                format: markdown
                disable_web_page_preview: true


